node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'NodeJS') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', '76a06bb5-e836-4815-9571-dc88cf50c077') {
       def app = docker.build("neil21975/jenkins-demo:${commit_id}", '.').push()
     }
     stage('docker run') {
     docker run -ti -p 8080:800 neil21975/jenkins-demo:${commit_id}
     }
   }
}
